export const SET_CURRENT_ANIMAL = 'SET_CURRENT_ANIMAL';
export const ADD_ANIMAL = 'ADD_ANIMAL';
export const REMOVE_ANIMAL = 'REMOVE_ANIMAL';
export const RESET_ANIMALS = 'RESET_ANIMALS';

export const ANIMAL_ACTIONS = new Set([ SET_CURRENT_ANIMAL, ADD_ANIMAL, REMOVE_ANIMAL,
  RESET_ANIMALS, ]);
