export const ANIMALS = [
  'Albatross',
  'Alligators',
  'Apes',
  'Antelope',
  'Ants',
  'Asses',
  'Auks',
  'Baboons',
  'Bacteria',
  'Badgers',
  'Barracudas',
  'Bats',
  'Bass',
  'Bears',
  'Bears',
  'Beavers',
  'Bees',
  'Birds',
  'Birds',
  'Birds',
  'Birds',
  'Birds',
  'Bison',
  'Bitterns',
  'Bloodhounds',
  'Bobolinks',
  'Buffalo',
  'Bullfinches',
  'Bullocks',
  'Butterflies',
  'Buzzards',
  'Camels',
  'Capons',
  'Caribou',
  'Caterpillars',
  'Cats',
  'Cats',
  'Cats',
  'Cattle',
  'Cheetahs',
  'Chickens',
  'Chickens',
  'Chinchilla',
  'Choughs',
  'Clams',
  'Cobras',
  'Cockroaches',
  'Cod',
  'Coots',
  'Cormorants',
  'Cows',
  'Coyotes',
  'Crabs',
  'Cranes',
  'Crocodiles',
  'Crows',
  'Curlews',
  'Deer',
  'Deer',
  'Deer',
  'Dogs',
  'Dogs',
  'Dogs',
  'Dogs',
  'Dogs',
  'Dolphins',
  'Donkeys',
  'Dotterel',
  'Doves',
  'Doves',
  'Ducks',
  'Ducks',
  'Ducks',
  'Dunlins',
  'Eagles',
  'Eels',
  'Elephants',
  'Elk',
  'Emus',
  'Falcons',
  'Ferrets',
  'Finches',
  'Fish',
  'Fish',
  'Flamingoes',
  'Flies',
  'Frogs',
  'Fox',
  'Geese',
  'Geese',
  'Geese',
  'Giraffes',
  'Gnats',
  'Gnus',
  'Goats',
  'Goldfinches',
  'Goldfish',
  'Gorillas',
  'Goshawks',
  'Grasshoppers',
  'Greyhounds',
  'Grouse',
  'Guillemots',
  'Gulls',
  'Guinea',
  'Hawks',
  'Hawks',
  'Hawks',
  'Hedgehogs',
  'Herons',
  'Herring',
  'Hippopotamuses',
  'Hornets',
  'Horses',
  'Horses',
  'Horses',
  'Horses',
  'Hummingbirds',
  'Hyenas',
  'Impalas',
  'Insects',
  'Jays',
  'Jellyfish',
  'Kangaroos',
  'Lapwings',
  'Larks',
  'Leopards',
  'Lice',
  'Lions',
  'Lizards',
  'Locusts',
  'Magpies',
  'Mallards',
  'Mallards',
  'Martens',
  'Mice',
  'Midges',
  'Minnows',
  'Moles',
  'Monkeys',
  'Moose',
  'Mosquitoes',
  'Mudhens',
  'Mules',
  'Nightingales',
  'Otters',
  'Owls',
  'Oxen',
  'Oysters',
  'Parrots',
  'Partridge',
  'Peacocks',
  'Pekingese',
  'Pelicans',
  'Penguins',
  'Penguins',
  'Pheasants',
  'Pheasants',
  'Pheasants',
  'Pigeons',
  'Pigs',
  'Pigs',
  'Pigs',
  'Pigs',
  'Pigs',
  'Pilchards',
  'Plovers',
  'Plovers',
  'Polecats',
  'Porcupines',
  'Porpoises',
  'Prairie',
  'Ptarmigans',
  'Quail',
  'Rabbits',
  'Rabbits',
  'Rabbits',
  'Rabbits',
  'Rabbits',
  'Raccoons',
  'Rats',
  'Rattlesnakes',
  'Ravens',
  'Reindeer',
  'Rhinoceroses',
  'Roebucks',
  'Rooks',
  'Ruffs',
  'Salamandars',
  'Salmon',
  'Sandpipers',
  'Sardines',
  'Scorpions',
  'Seabirds',
  'Seals',
  'Sharks',
  'Sheep',
  'Sheldrakes',
  'Skylarks',
  'Squirrels',
  'Snails',
  'Snakes',
  'Snipe',
  'Sparrows',
  'Spiders',
  'Springbok',
  'Squirrels',
  'Starlings',
  'Stingrays',
  'Stoats',
  'Storks',
  'Swallows',
  'Swans',
  'Swans',
  'Swifts',
  'Teal',
  'Termites',
  'Thrush',
  'Tigers',
  'Toads',
  'Trout',
  'Turkeys',
  'Turtles',
  'Turtle',
  'Vipers',
  'Vultures',
  'Vultures',
  'Walruses',
  'Wasps',
  'Waterfowl',
  'Weasles',
  'Whales',
  'Widgeons',
  'Wildfowl',
  'Wolves',
  'Wolves',
  'Wombats',
  'Woodcocks',
  'Woodpeckers',
  'Worms',
  'Wrens',
  'Zebras',
];

export const NAMES = [
  [ 'Rookery', ],
  [ 'Congregation', ],
  [ 'Shrewdness, Troop', ],
  [ 'Herd', ],
  [ 'Colony, Army, Swarm, Nest', ],
  [ 'Pace, Herd, Drove', ],
  [ 'Colony, Flock, Raft', ],
  [ 'Troop, Flange', ],
  [ 'Culture', ],
  [ 'Cete, Colony, Set, Company', ],
  [ 'Battery', ],
  [ 'Colony, Cloud', ],
  [ 'Shoal', ],
  [ 'Sloth, Sleuth', ],
  [ 'Litter', ],
  [ 'Colony, Family', ],
  [ 'Grist, Hive, Swarm, Nest', ],
  [ 'Brood, Clutch', ],
  [ 'Flight', ],
  [ 'Volary, Brace, Plump, Knob', ],
  [ 'Flock, Dissimulation', ],
  [ 'Wreck', ],
  [ 'Herd', ],
  [ 'Sedge, Seige', ],
  [ 'Sute', ],
  [ 'Chain', ],
  [ 'Herd, Troop, Gang, Obstinancy', ],
  [ 'Bellowing', ],
  [ 'Drove', ],
  [ 'Flight, Flutter', ],
  [ 'Wake', ],
  [ 'Caravan, Train, Flock', ],
  [ 'Mews', ],
  [ 'Herd', ],
  [ 'Army', ],
  [ 'Clowder, Clutter, Pounce, Dout, Nuisance, Glorying, Glare', ],
  [ 'Kindle, Litter, Intrigue', ],
  [ 'Destruction', ],
  [ 'Drove, Herd, Team', ],
  [ 'Coalition', ],
  [ 'Brood, Peep', ],
  [ 'Clutch, Chattering', ],
  [ 'Colony', ],
  [ 'Clattering', ],
  [ 'Bed', ],
  [ 'Quiver', ],
  [ 'Intrusion', ],
  [ '', ],
  [ 'Cover, Raft', ],
  [ 'Gulp', ],
  [ 'Kine', ],
  [ 'Band', ],
  [ 'Cast', ],
  [ 'Sedge, Seige', ],
  [ 'Bask, Float', ],
  [ 'Murder, Horde, Parcel, Storytelling', ],
  [ 'Herd', ],
  [ 'Herd, Leash, Gang', ],
  [ 'Brace, Clash', ],
  [ 'Bevy', ],
  [ 'Kennel', ],
  [ 'Cowardice', ],
  [ 'Cry, Mute, Pack', ],
  [ 'Litter', ],
  [ 'Pack', ],
  [ 'Pod', ],
  [ 'Drove, Pace, Herd', ],
  [ 'Trip', ],
  [ 'Dule, Bevy, Cote, Dole, Paddling', ],
  [ 'Pitying, Piteousness', ],
  [ 'Flock', ],
  [ 'Brace, badling', ],
  [ 'Raft, Team, Paddling', ],
  [ 'Fling', ],
  [ 'Convocation, Aerie', ],
  [ 'Swarm, Bed, Fry', ],
  [ 'Herd, Memory', ],
  [ 'Herd', ],
  [ 'Mob', ],
  [ 'Cast', ],
  [ 'Business, Cast, Fesnying', ],
  [ 'Charm', ],
  [ 'Draft, Nest, Shoal, School', ],
  [ 'Catch, Drought, Haul', ],
  [ 'Stand, Flamboyance', ],
  [ 'Business, Swarm, Cloud', ],
  [ 'Army, Colony, Knot', ],
  [ 'Skulk, Earth, Lead, Troop', ],
  [ 'Flock', ],
  [ 'Skein', ],
  [ 'Gaggle, Herd, Corps', ],
  [ 'Tower', ],
  [ 'Cloud, Horde, Swarm', ],
  [ 'Implausibility', ],
  [ 'Tribe, Trip, Drove, Herd, Flock', ],
  [ 'Charm', ],
  [ 'Glint, Troubling', ],
  [ 'Band, Troop', ],
  [ 'Flight', ],
  [ 'Cloud', ],
  [ 'Leash', ],
  [ 'Pack, Covey', ],
  [ 'Bazaar', ],
  [ 'Colony, Screech', ],
  [ 'Confusion', ],
  [ 'Cast', ],
  [ 'Kettle', ],
  [ 'Boil', ],
  [ 'Array', ],
  [ 'Sedge, Siege, Hedge', ],
  [ 'Army, Shoal', ],
  [ 'Bloat', ],
  [ 'Nest, Bike', ],
  [ 'Team, Harras, Stable, Troop, Stud (a group belonging to one owner', ],
  [ 'Rag, Rake', ],
  [ 'String', ],
  [ 'Herd', ],
  [ 'Charm', ],
  [ 'Cackle, Clan', ],
  [ 'Herd', ],
  [ 'Horde, Nest, Swarm, Rabble, Plague', ],
  [ 'Party, Scold, Band', ],
  [ 'Smack, Brood', ],
  [ 'Troop, Mob, Herd', ],
  [ 'Deceit', ],
  [ 'Exaltation, Ascension', ],
  [ 'Leap', ],
  [ 'Flock', ],
  [ 'Pride, Sault, Troop', ],
  [ 'Lounge', ],
  [ 'Plague', ],
  [ 'Tiding, Gulp, Murder, Charm', ],
  [ 'Brace', ],
  [ 'Sord', ],
  [ 'Richness', ],
  [ 'Mischief', ],
  [ 'Bite', ],
  [ 'Shoal, Steam, Swarm', ],
  [ 'Labor, Company, Movement', ],
  [ 'Troop, Barrel, Carload, Cartload, Tribe', ],
  [ 'Herd', ],
  [ 'Scourge', ],
  [ 'Fleet', ],
  [ 'Pack, Span, Barren, Rake', ],
  [ 'Watch', ],
  [ 'Romp, Bevy, Family, Raft', ],
  [ 'Parliament, Stare', ],
  [ 'Team, Yoke, Drove', ],
  [ 'Bed', ],
  [ 'Company, Pandemonium', ],
  [ 'Covey, Bew', ],
  [ 'Muster, Ostentation, Pride', ],
  [ 'Pomp', ],
  [ 'Pod', ],
  [ 'Colony, Rookery, Huddle', ],
  [ 'Cr�che', ],
  [ 'Nest, Nye', ],
  [ 'Nide', ],
  [ 'Bouquet', ],
  [ 'Flight, Flock, Kit', ],
  [ 'Drift, Drove', ],
  [ 'Singular, Sounder', ],
  [ 'Team, Passel, Drift, Parcel', ],
  [ 'Litter, Farrow', ],
  [ 'Sounder', ],
  [ 'Shoal', ],
  [ 'Congregation', ],
  [ 'Wing', ],
  [ 'Chine', ],
  [ 'Prickle', ],
  [ 'Herd, Pod, School, Crowd, Shoal', ],
  [ 'Coterie', ],
  [ 'Covey', ],
  [ 'Bevy, Covey', ],
  [ 'Colony, Warren, Bury, Trace, Trip', ],
  [ 'Herd', ],
  [ 'Down, Husk', ],
  [ 'Husk', ],
  [ 'Litter, Nest', ],
  [ 'Gaze', ],
  [ 'Colony, Pack, Plague, Swarm', ],
  [ 'Rhumba', ],
  [ 'Unkindness, Storytelling', ],
  [ 'Herd', ],
  [ 'Crash, Stubbornness', ],
  [ 'Bevy', ],
  [ 'Building, Clamor, Parliament', ],
  [ 'Hill', ],
  [ 'Congress', ],
  [ 'Run', ],
  [ 'Fling', ],
  [ 'Family', ],
  [ 'Bed, Nest', ],
  [ 'Wreck', ],
  [ 'Pod, Bob, Harem, Herd, Rookery', ],
  [ 'Shiver, School, Shoal', ],
  [ 'Drove, Flock, Down, Hurtle, Fold, Pack, Trip', ],
  [ 'Doading', ],
  [ 'Exultation', ],
  [ 'Dray, Scurry', ],
  [ 'Escargatoire, Rout, Walk', ],
  [ 'Den, Nest, Pit, Bed, Knot', ],
  [ 'Walk, Wisp', ],
  [ 'Host', ],
  [ 'Cluster, Clutter', ],
  [ 'Herd', ],
  [ 'Dray, Scurry', ],
  [ 'Murmuration, Chattering', ],
  [ 'Fever', ],
  [ 'Pack, Trip', ],
  [ 'Mustering, Muster', ],
  [ 'Flight, Gulp', ],
  [ 'Bevy, Bank, Herd', ],
  [ 'Wedge, Flight', ],
  [ 'Flock', ],
  [ 'Spring', ],
  [ 'Colony, Nest, Swarm, Brood', ],
  [ 'Mutation', ],
  [ 'Streak, Ambush', ],
  [ 'Knot, Knab, Nest', ],
  [ 'Hover', ],
  [ 'Rafter, Gang, Posse', ],
  [ 'Bale, Nest, Turn, Dole', ],
  [ 'Pitying, Dule', ],
  [ 'Generation, Nest', ],
  [ 'Venue', ],
  [ 'Kettle', ],
  [ 'Herd, Pod', ],
  [ 'Nest, Swarm', ],
  [ 'Knob, Plump', ],
  [ 'Gang, Colony, Pack', ],
  [ 'Pod, Gam, Herd, School, Mod', ],
  [ 'Company', ],
  [ 'Plump', ],
  [ 'Pack', ],
  [ 'Route, Rout', ],
  [ 'Wisdom', ],
  [ 'Fall', ],
  [ 'Descent', ],
  [ 'Bed, Clew, Bunch, Clat', ],
  [ 'Herd', ],
  [ 'Zeal, Crossing, Dazzle, Cohorts, Herd', ],
];

export const splitNames = str => str.split(',');
